# Generated by Django 3.2.8 on 2021-10-30 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=64, verbose_name='Имя клиента')),
                ('phone_number', models.CharField(max_length=32, verbose_name='Номер телефона')),
                ('date_application', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата подачи заявления')),
            ],
            options={
                'verbose_name': 'Контактные данные',
                'verbose_name_plural': 'Контактные данные',
                'ordering': ['date_application'],
            },
        ),
        migrations.CreateModel(
            name='SubscribeToNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_email', models.EmailField(max_length=64, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Подписка на рассылку',
                'verbose_name_plural': 'Подписки на рассылку',
            },
        ),
    ]
