# Generated by Django 3.2.8 on 2021-10-31 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0002_auto_20211031_1744'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicesubsection',
            options={'verbose_name': 'Подраздел услуги', 'verbose_name_plural': 'Подразделы услуг'},
        ),
    ]
