# Generated by Django 3.2.8 on 2021-10-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0003_alter_servicesubsection_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(upload_to='base_app/static/base_app/img/services/service', verbose_name='Изображение услуги'),
        ),
        migrations.AlterField(
            model_name='servicesubsection',
            name='image',
            field=models.ImageField(upload_to='base_app/img/services/service_subsection', verbose_name='Изображение подраздела услуги'),
        ),
    ]
