# Generated by Django 3.2.8 on 2021-10-31 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0004_auto_20211031_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesubsection',
            name='image',
            field=models.ImageField(upload_to='base_app/static/base_app/img/services/service_subsection', verbose_name='Изображение подраздела услуги'),
        ),
    ]
