# Generated by Django 3.2.8 on 2021-10-31 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0005_alter_servicesubsection_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='subsections',
        ),
        migrations.AddField(
            model_name='servicesubsection',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base_app.service', verbose_name='Услуга'),
        ),
    ]
