# Generated by Django 3.2.8 on 2021-10-31 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0006_auto_20211031_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('description_1', models.TextField(verbose_name='Первая часть описания')),
                ('description_2', models.TextField(verbose_name='Вторая часть описания')),
                ('image_1', models.ImageField(upload_to='base_app/static/base_app/img/FAQ', verbose_name='Первое изображение')),
                ('image_2', models.ImageField(upload_to='base_app/static/base_app/img/FAQ', verbose_name='Второе изображение')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Часто задаваемые вопросы',
            },
        ),
    ]
