# Generated by Django 3.2.8 on 2021-10-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_app', '0007_itemfaq'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
    ]
